import type { AssumptionMeta, Assumptions } from "./types";

/**
 * Single source of truth for the NIZEK business model.
 * Placeholder defaults — swap these values for real figures and the entire
 * site (every chart, KPI, return figure) updates with no other change.
 */
export const HORIZON_YEARS = 7;

export const defaultAssumptions: Assumptions = {
  startingCustomers: 38,
  newCustomersMonth1: 5,
  acquisitionGrowth: 1.9,
  arpa: 3400,
  annualPriceIncrease: 3,
  monthlyChurn: 1.4,
  netExpansion: 108,
  grossMargin: 74,
  cac: 26000,
  rdPercent: 26,
  gaPercent: 14,
  fixedOpexMonthly: 260000,
  startingCash: 1800000,
  roundSize: 6000000,
  preMoney: 24000000,
  followOnYear: 3,
  followOnSize: 18000000,
  followOnPre: 90000000,
  exitYear: 6,
  exitMultiple: 7,
  investorTicket: 1000000,
  optionPool: 10,
};


export const assumptionMeta: AssumptionMeta[] = [
  {
    key: "newCustomersMonth1",
    label: "New clients / month",
    group: "Growth",
    unit: "number",
    min: 1,
    max: 40,
    step: 1,
    help: "New logos acquired in the first projected month.",
  },
  {
    key: "acquisitionGrowth",
    label: "Acquisition growth",
    group: "Growth",
    unit: "percent",
    min: 0,
    max: 12,
    step: 0.1,
    help: "Month-over-month growth in new logo acquisition.",
  },
  {
    key: "startingCustomers",
    label: "Starting clients",
    group: "Growth",
    unit: "number",
    min: 0,
    max: 400,
    step: 1,
    help: "Active clients at model start.",
  },
  {
    key: "monthlyChurn",
    label: "Monthly logo churn",
    group: "Retention",
    unit: "percent",
    min: 0,
    max: 6,
    step: 0.1,
    help: "Share of clients lost each month.",
  },
  {
    key: "netExpansion",
    label: "Net revenue retention",
    group: "Retention",
    unit: "percent",
    min: 80,
    max: 160,
    step: 1,
    help: "Annualised expansion within the retained base.",
  },
  {
    key: "arpa",
    label: "Average revenue / client",
    group: "Pricing",
    unit: "currency",
    min: 500,
    max: 20000,
    step: 100,
    help: "Monthly revenue per active client.",
  },
  {
    key: "annualPriceIncrease",
    label: "Annual price increase",
    group: "Pricing",
    unit: "percent",
    min: 0,
    max: 15,
    step: 0.5,
    help: "Yearly uplift applied to average contract value.",
  },
  {
    key: "grossMargin",
    label: "Gross margin",
    group: "Pricing",
    unit: "percent",
    min: 30,
    max: 95,
    step: 1,
    help: "Revenue remaining after delivery cost.",
  },
  {
    key: "cac",
    label: "Cost to acquire a client",
    group: "Costs",
    unit: "currency",
    min: 1000,
    max: 60000,
    step: 500,
    help: "Fully loaded sales and marketing cost per new logo.",
  },
  {
    key: "rdPercent",
    label: "R&D as % of revenue",
    group: "Costs",
    unit: "percent",
    min: 5,
    max: 60,
    step: 1,
    help: "Product and engineering spend.",
  },
  {
    key: "gaPercent",
    label: "G&A as % of revenue",
    group: "Costs",
    unit: "percent",
    min: 3,
    max: 40,
    step: 1,
    help: "General and administrative spend.",
  },
  {
    key: "fixedOpexMonthly",
    label: "Fixed operating base",
    group: "Costs",
    unit: "currency",
    min: 0,
    max: 600000,
    step: 10000,
    help: "Monthly cost base independent of revenue.",
  },
  {
    key: "startingCash",
    label: "Cash on hand",
    group: "Capital",
    unit: "currency",
    min: 0,
    max: 20000000,
    step: 100000,
    help: "Cash at model start, before this round.",
  },
  {
    key: "roundSize",
    label: "Round size",
    group: "Capital",
    unit: "currency",
    min: 1000000,
    max: 40000000,
    step: 500000,
    help: "Capital raised in the current round.",
  },
  {
    key: "preMoney",
    label: "Pre-money valuation",
    group: "Capital",
    unit: "currency",
    min: 5000000,
    max: 200000000,
    step: 1000000,
    help: "Valuation before the current round.",
  },
  {
    key: "optionPool",
    label: "Option pool",
    group: "Capital",
    unit: "percent",
    min: 0,
    max: 25,
    step: 1,
    help: "Employee pool reserved post-round.",
  },
  {
    key: "followOnYear",
    label: "Follow-on round year",
    group: "Capital",
    unit: "year",
    min: 2,
    max: 6,
    step: 1,
    help: "Year of the next financing.",
  },
  {
    key: "followOnSize",
    label: "Follow-on size",
    group: "Capital",
    unit: "currency",
    min: 0,
    max: 80000000,
    step: 1000000,
    help: "Capital raised in the follow-on round.",
  },
  {
    key: "followOnPre",
    label: "Follow-on pre-money",
    group: "Capital",
    unit: "currency",
    min: 20000000,
    max: 600000000,
    step: 5000000,
    help: "Valuation before the follow-on round.",
  },
  {
    key: "exitYear",
    label: "Exit year",
    group: "Exit",
    unit: "year",
    min: 3,
    max: HORIZON_YEARS,
    step: 1,
    help: "Year of liquidity event.",
  },
  {
    key: "exitMultiple",
    label: "Exit multiple on ARR",
    group: "Exit",
    unit: "multiple",
    min: 2,
    max: 20,
    step: 0.5,
    help: "Enterprise value as a multiple of exit-year ARR.",
  },
  {
    key: "investorTicket",
    label: "Your investment",
    group: "Exit",
    unit: "currency",
    min: 100000,
    max: 20000000,
    step: 100000,
    help: "Capital you deploy into the current round.",
  },
];

export const assumptionGroups = [
  "Growth",
  "Retention",
  "Pricing",
  "Costs",
  "Capital",
  "Exit",
] as const;

export const metaFor = (key: string) =>
  assumptionMeta.find((m) => m.key === key)!;
